# This workflow checks notebook html pages deployed to github.io for broken links.

on:
  workflow_dispatch:

jobs:
  find_broken_links:
    runs-on: ubuntu-latest
    name: Check for broken links
    steps:
      - name: Check for broken links
        uses: ScholliYT/Broken-Links-Crawler-Action@v3
        with:
          website_url: "https://spacetelescope.github.io/hst_notebooks/"
          resolve_before_filtering: 'true'
          verbose: 'Error'
          max_retry_time: 30
          max_retries: 5
