# This workflow checks notebook html pages deployed to github.io for broken links.

on:
  workflow_dispatch:

jobs:
  broken_link_checker_job:
    runs-on: ubuntu-latest
    name: Check for broken links
    steps:
      - name: Check for broken links
        id: link-report
        uses: celinekurpershoek/link-checker@v1.0.2
        with:
          # Required:
          url: "https://spacetelescope.github.io/hst_notebooks/"
          # optional:
          honorRobotExclusions: false
          recursiveLinks: true # Check all URLs on all reachable pages (could take a while)
      - name: Get the result
        run: echo "${{steps.link-report.outputs.result}}"
