# This workflow checks notebook html pages deployed to github.io for broken links.

on:
  workflow_call:
    inputs:
      website_url:
        default: https://spacetelescope.github.io/${{ github.event.repository.name }}
        description: "The URL of the website to check."
        required: false
        type: 'string'

jobs:
  find_broken_links:
    runs-on: ubuntu-latest
    name: Evaluation of ${{ inputs.website_url }} for broken links
    steps:
      - name: Broken-Links-Crawler
        uses: ScholliYT/Broken-Links-Crawler-Action@v3.3.0
        with:
          website_url: ${{ inputs.website_url }}
          resolve_before_filtering: 'true'
          verbose: 'Error'
          max_retry_time: 30
          max_retries: 5
