name: HTML Accessibility Check

on:
  workflow_call:
    inputs:
      target_url:
        type: 'string'
        description: "URL to scan"
        required: false
        default: https://spacetelescope.github.io/${{ github.event.repository.name }}

jobs:
  a11yWatchRun:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Web Accessibility Evaluation of ${{ inputs.target_url }}/intro.html<<<<<<<
        uses: a11ywatch/github-actions@v2.1.8
        with:
          WEBSITE_URL: ${{ inputs.target_url }}/intro.html
          SITE_WIDE: true
          SUBDOMAINS: true
          SITEMAP: true
          UPGRADE: true
          LIST: true
          EXTERNAL: false
          UPLOAD: true
          FAIL_ERRORS_COUNT: 1
