name: HTML Accessibility Check

on:
  workflow_call:
    inputs:
      target_url:
        required: true
        type: string
jobs:
  a11yWatchRun:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Web Accessibility Evaluation on ${{ vars.target_url }}
        uses: a11ywatch/github-actions@v2.1.6
        with:
          WEBSITE_URL: ${{ vars.target_url }}
          SITE_WIDE: true
          SUBDOMAINS: true
          SITEMAP: true
          UPGRADE: true
          LIST: true
          EXTERNAL: false
          UPLOAD: true