name: HTML Accessibility Check

on:
  workflow_call:

jobs:
  a11yWatchRun:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Web Accessibility Evaluation of https://spacetelescope.github.io/mast_notebooks/
        uses: a11ywatch/github-actions@v2.1.6
        with:
          WEBSITE_URL: https://spacetelescope.github.io/mast_notebooks/
          SITE_WIDE: true
          SUBDOMAINS: true
          SITEMAP: true
          UPGRADE: true
          LIST: true
          EXTERNAL: false
          UPLOAD: true
          FAIL_TOTAL_COUNT: 1
